const gamesNameMap = {
  ANN: 'Annihilation',
  BB: 'BuildBattle',
  BP: 'BlockParty',
  BW: 'BedWars',
  CP: 'ClashPoint',
  DR: 'DeathRun',
  DUELS: 'Duels',
  GG: 'GunGame',
  HG: 'HungerGames',
  KPVP: 'KitPvP',
  MW: 'MobWars',
  PRISON: 'Prison',
  SW: 'SkyWars',
  ARC: 'Аркады',
  BRIDGE: 'The Bridge',
  JUMPLEAGUE: 'Jump League',
  MURDER: 'Murder Mystery',
  PAINTBALL: 'Paintball',
  SHEEP: 'Sheep Wars',
  TURFWARS: 'Turf Wars',
  SPLEEF: 'Spleef',
  TNTTAG: 'TNT Tag',
  TNTRUN: 'TNT Run',
};

export default gamesNameMap;
